
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
    - job: FirstJob
      steps:
        - bash: echo build started for First job.
    - job: SecondJob
      steps:
        - bash: echo build started for Second job.     
- stage: DevDeploy
  jobs:
    - job: DevDeployJob
      steps:
        - bash:  echo Dev deploy job started.
- stage: QADeploy
  jobs:
    - job: QADeployJob
      steps:
        - bash: echo QA deploy job started.
- stage: ProdDeploy
  jobs:
    - job: ProdDeployJob
      steps:
        - bash: echo Prod Deploy Job stated.
  

